import {
  createSubtitleEditor,
  serializeSubtitles,
  setLocale,
  type EditorCommand,
  type SubtitleEditorHandle,
} from "../src/index";
import { importPlainText } from "../src/formats/plaintext";
import { listAutosaveVersions, listRecentProjects, loadLastProject, saveLastProject } from "./project-store";

const editorEl = document.getElementById("editor")!;
const fileInput = document.getElementById("file") as HTMLInputElement;
const mediaInput = document.getElementById("media-file") as HTMLInputElement;
const openBtn = document.getElementById("open") as HTMLButtonElement;
const newBtn = document.getElementById("new") as HTMLButtonElement;
const mediaBtn = document.getElementById("open-media") as HTMLButtonElement;
const saveBtn = document.getElementById("save") as HTMLButtonElement;
const toolsBtn = document.getElementById("tools") as HTMLButtonElement;
const languageSelect = document.getElementById("language") as HTMLSelectElement;
const themeButton = document.getElementById("theme") as HTMLButtonElement;
const rateSelect = document.getElementById("playback-rate") as HTMLSelectElement;
const appFormatSelect = document.getElementById("app-format") as HTMLSelectElement;
const installBtn = document.getElementById("install") as HTMLButtonElement;
const filenameEl = document.getElementById("filename")!;
const statusEl = document.getElementById("status-text")!;
const autosaveEl = document.getElementById("autosave-status")!;
const dropOverlay = document.getElementById("drop-overlay")!;
const mainToolbar = document.querySelector<HTMLElement>(".quickbar")!;

let handle: SubtitleEditorHandle | null = null;
let currentFilename = "untitled.ass";
let autosaveTimer = 0;
let dirty = false;
let documentVersion = 0;
const appEvents: string[] = [];
const recentMediaFiles: File[] = [];

const savedLocale = localStorage.getItem("aegisub-web.locale") || "";
const browserLocale = navigator.language.toLowerCase().startsWith("zh") ? "zh" :
  navigator.language.toLowerCase().startsWith("ja") ? "ja" :
    navigator.language.toLowerCase().startsWith("fr") ? "fr" : "en";
languageSelect.value = savedLocale || browserLocale;
setLocale(languageSelect.value);
document.documentElement.lang = languageSelect.value === "zh" ? "zh-CN" : languageSelect.value;

const SAMPLE_ASS = [
  "[Script Info]",
  "; Generated by Aegisub Web",
  "Title: Welcome to Aegisub Web",
  "ScriptType: v4.00+",
  "WrapStyle: 0",
  "ScaledBorderAndShadow: yes",
  "PlayResX: 1920",
  "PlayResY: 1080",
  "",
  "[V4+ Styles]",
  "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
  "Style: Default,Arial,64,&H00FFFFFF,&H0000B6FF,&H00101010,&H78000000,0,0,0,0,100,100,0,0,1,3,1,2,90,90,54,1",
  "",
  "[Events]",
  "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  "Dialogue: 0,0:00:01.00,0:00:04.00,Default,,0,0,0,,欢迎使用 Aegisub Web",
  "Dialogue: 0,0:00:04.20,0:00:07.20,Default,,0,0,0,,加载视频、查看波形并精确打轴",
  "Dialogue: 0,0:00:07.40,0:00:10.40,Default,,0,0,0,,ASS 样式、卡拉 OK 与矢量特效",
].join("\n");

function logEvent(message: string): void {
  appEvents.unshift(`${new Date().toLocaleTimeString()}  ${message}`);
  if (appEvents.length > 200) appEvents.length = 200;
}

function showShellDialog(title: string, build: (body: HTMLDivElement, close: () => void) => void): void {
  document.querySelector(".shell-dialog")?.remove();
  const dialog = document.createElement("dialog");
  dialog.className = "shell-dialog";
  const head = document.createElement("header");
  const heading = document.createElement("h2");
  heading.textContent = title;
  const closeButton = document.createElement("button");
  closeButton.textContent = "×";
  head.append(heading, closeButton);
  const body = document.createElement("div");
  body.className = "shell-dialog-body";
  const close = (): void => dialog.close();
  closeButton.addEventListener("click", close);
  build(body, close);
  dialog.append(head, body);
  dialog.addEventListener("close", () => dialog.remove());
  document.body.append(dialog);
  dialog.showModal();
}

function showOptions(): void {
  showShellDialog("Aegisub Web 设置", (body, close) => {
    const fields: [string, string, string][] = [
      ["Lead-in (ms)", "aegisub-web.lead-in", "100"],
      ["Lead-out (ms)", "aegisub-web.lead-out", "100"],
    ];
    for (const [labelText, key, fallback] of fields) {
      const label = document.createElement("label");
      label.textContent = labelText;
      const input = document.createElement("input");
      input.type = "number";
      input.value = localStorage.getItem(key) ?? fallback;
      input.addEventListener("change", () => localStorage.setItem(key, input.value));
      label.append(input);
      body.append(label);
    }
    const spell = document.createElement("label");
    const spellInput = document.createElement("input");
    spellInput.type = "checkbox";
    spellInput.checked = localStorage.getItem("aegisub-web.spellcheck") !== "false";
    spellInput.addEventListener("change", () => localStorage.setItem("aegisub-web.spellcheck", String(spellInput.checked)));
    spell.append(spellInput, document.createTextNode(" 启用浏览器拼写检查"));
    body.append(spell);
    const done = document.createElement("button");
    done.textContent = "完成";
    done.addEventListener("click", close);
    body.append(done);
  });
}

function showLog(): void {
  showShellDialog("事件日志", (body) => {
    const pre = document.createElement("pre");
    pre.textContent = appEvents.join("\n") || "暂无事件。";
    body.append(pre);
  });
}

async function showRecentSubtitles(): Promise<void> {
  const recent = await listRecentProjects();
  showShellDialog("最近字幕", (body, close) => {
    if (!recent.length) body.textContent = "暂无最近字幕。";
    for (const project of recent) {
      const button = document.createElement("button");
      button.textContent = `${project.filename} · ${new Date(project.updatedAt).toLocaleString()}`;
      button.addEventListener("click", () => {
        openDocument(project.text, project.filename, false);
        close();
      });
      body.append(button);
    }
  });
}

async function showAutosaveVersions(): Promise<void> {
  const versions = await listAutosaveVersions();
  showShellDialog("自动保存版本", (body, close) => {
    if (!versions.length) body.textContent = "暂无自动保存版本。";
    let lastFile = "";
    for (const version of versions) {
      if (version.filename !== lastFile) {
        const heading = document.createElement("strong"); heading.textContent = version.filename; body.append(heading); lastFile = version.filename;
      }
      const button = document.createElement("button");
      button.textContent = new Date(version.updatedAt).toLocaleString();
      button.addEventListener("click", () => { openDocument(version.text, version.filename, false); close(); });
      body.append(button);
    }
  });
}

function openWithCharset(): void {
  const input = document.createElement("input");
  input.type = "file";
  input.accept = fileInput.accept;
  input.addEventListener("change", async () => {
    const file = input.files?.[0];
    if (!file) return;
    const charset = prompt("字符编码（utf-8 / gb18030 / big5 / shift_jis 等）:", "utf-8") || "utf-8";
    try {
      const text = new TextDecoder(charset).decode(await file.arrayBuffer());
      openDocument(text, file.name);
      logEvent(`以 ${charset} 打开 ${file.name}`);
    } catch (error) {
      updateChrome(error instanceof Error ? error.message : String(error));
    }
  });
  input.click();
}

function runShellAegisubCommand(command: string): boolean {
  const links: Record<string, string> = {
    "help/bugs": "https://github.com/samgum/aegisub-web/issues",
    "help/contents": "https://github.com/samgum/aegisub-web#readme",
    "help/irc": "https://web.libera.chat/#aegisub",
    "help/video": "https://aegisub.org/docs/latest/visual_typesetting/",
    "help/website": "https://aegisub.org/",
  };
  if (links[command]) {
    window.open(links[command], "_blank", "noopener");
    return true;
  }
  switch (command) {
    case "app/language": {
      showShellDialog("界面语言 / Interface Language", (body, close) => {
        for (const option of languageSelect.options) {
          const control = document.createElement("button");
          control.textContent = `${option.value === languageSelect.value ? "✓ " : ""}${option.textContent ?? option.value}`;
          control.addEventListener("click", () => {
            languageSelect.value = option.value;
            languageSelect.dispatchEvent(new Event("change"));
            close();
          });
          body.append(control);
        }
      });
      return true;
    }
    case "app/log": showLog(); return true;
    case "app/new_window": window.open(location.href, "_blank", "noopener"); return true;
    case "app/options": showOptions(); return true;
    case "app/toggle/global_hotkeys": {
      const enabled = localStorage.getItem("aegisub-web.global-hotkeys") !== "true";
      localStorage.setItem("aegisub-web.global-hotkeys", String(enabled));
      updateChrome(`全局热键覆盖：${enabled ? "开" : "关"}`);
      return true;
    }
    case "app/updates": {
      void navigator.serviceWorker?.getRegistration().then(async (registration) => {
        await registration?.update();
        updateChrome("已检查更新；重新载入即可使用最新版本。");
      });
      return true;
    }
    case "app/exit": window.close(); updateChrome("浏览器不允许页面自行关闭时，请关闭当前标签页。"); return true;
    case "app/minimize": updateChrome("浏览器标签页的最小化由系统窗口管理器控制。"); return true;
    case "app/maximize": void document.documentElement.requestFullscreen?.(); return true;
    case "app/bring_to_front": window.focus(); return true;
    case "subtitle/new": newDocument(); return true;
    case "subtitle/close": newDocument(); return true;
    case "subtitle/open": fileInput.click(); return true;
    case "subtitle/open/autosave": void showAutosaveVersions(); return true;
    case "subtitle/open/charset": openWithCharset(); return true;
    case "subtitle/open/video": mediaInput.click(); return true;
    case "subtitle/save":
    case "subtitle/save/as": handle?.runCommand("save"); return true;
    case "recent/subtitle/": void showRecentSubtitles(); return true;
    case "recent/audio/":
    case "recent/video/": {
      showShellDialog("最近媒体", (body, close) => {
        if (!recentMediaFiles.length) body.textContent = "本次会话尚未打开媒体。";
        for (const file of recentMediaFiles) {
          const button = document.createElement("button");
          button.textContent = file.name;
          button.addEventListener("click", () => { handle?.loadPreviewMedia(file); close(); });
          body.append(button);
        }
      });
      return true;
    }
    case "recent/keyframes/":
    case "recent/timecodes/": updateChrome("关键帧和时间码历史由当前项目会话保存。"); return true;
    default: return false;
  }
}

function updateChrome(message?: string): void {
  filenameEl.textContent = `${dirty ? "* " : ""}${currentFilename} - Aegisub Web`;
  document.title = `${dirty ? "● " : ""}${currentFilename} — Aegisub Web`;
  if (message) statusEl.textContent = message;
  if (handle) {
    const count = handle.getDoc().cues.length;
    statusEl.textContent = message || `${currentFilename} · ${count} 行字幕 · ${handle.getDoc().format.toUpperCase()}`;
  }
}

function scheduleAutosave(): void {
  window.clearTimeout(autosaveTimer);
  autosaveEl.textContent = "正在等待自动保存…";
  autosaveTimer = window.setTimeout(async () => {
    if (!handle) return;
    await saveLastProject({ filename: currentFilename, text: handle.getText(), updatedAt: Date.now() });
    autosaveEl.textContent = `已自动保存 ${new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`;
  }, 700);
}

function openDocument(text: string, filename: string, persist = true): void {
  documentVersion += 1;
  currentFilename = filename || "untitled.ass";
  dirty = false;

  const win = window as unknown as Record<string, unknown>;
  win.subChangeCount = 0;
  win.subSelections = [];
  if (handle) {
    handle.loadDocument({ text, filename: currentFilename });
  } else {
    editorEl.textContent = "";
    handle = createSubtitleEditor(editorEl, { text, filename: currentFilename }, {
      locale: languageSelect.value,
      spellcheck: localStorage.getItem("aegisub-web.spellcheck") !== "false",
      onAegisubCommand: runShellAegisubCommand,
      onChange: () => {
        win.subChangeCount = (win.subChangeCount as number) + 1;
        dirty = true;
        updateChrome();
        scheduleAutosave();
      },
      onSelectionChanged: (cueId) => {
        win.subSelection = cueId;
        (win.subSelections as unknown[]).push(cueId);
      },
    });
  }
  win.subHandle = handle;
  win.createSubtitleEditor = createSubtitleEditor;
  rateSelect.value = String(handle.getPlaybackRate());
  appFormatSelect.value = handle.getDoc().format;
  updateChrome();
  logEvent(`打开字幕 ${currentFilename}`);
  if (persist) scheduleAutosave();
}

async function openSubtitleFile(file: File): Promise<void> {
  try {
    const text = await file.text();
    if (/\.txt$/i.test(file.name) && !/--> |^WEBVTT|^\[Script Info\]|^\{\d+\}\{\d+\}/im.test(text)) {
      const actorSeparator = prompt("Actor separator:", localStorage.getItem("aegisub-web.text-import-actor") ?? ":") ?? ":";
      const commentStarter = prompt("Comment starter:", localStorage.getItem("aegisub-web.text-import-comment") ?? "#") ?? "#";
      const includeBlank = confirm("Include blank lines as comments?");
      localStorage.setItem("aegisub-web.text-import-actor", actorSeparator);
      localStorage.setItem("aegisub-web.text-import-comment", commentStarter);
      const doc = importPlainText(text, { actorSeparator, commentStarter, includeBlank });
      openDocument(serializeSubtitles(doc), file.name.replace(/\.txt$/i, ".ass"));
    } else openDocument(text, file.name);
  } catch (error) {
    updateChrome(error instanceof Error ? error.message : "无法读取该字幕文件");
  }
}

function newDocument(): void {
  openDocument(SAMPLE_ASS.replace("Welcome to Aegisub Web", "Untitled").replace(/Dialogue:.*(?:\n|$)/g, ""), "untitled.ass");
}

function run(command: EditorCommand): void {
  handle?.runCommand(command);
}

openBtn.addEventListener("click", () => fileInput.click());
fileInput.addEventListener("change", async () => {
  const file = fileInput.files?.[0];
  if (file) await openSubtitleFile(file);
  fileInput.value = "";
});
newBtn.addEventListener("click", newDocument);
mediaBtn.addEventListener("click", () => mediaInput.click());
mediaInput.addEventListener("change", () => {
  const file = mediaInput.files?.[0];
  if (file) {
    recentMediaFiles.unshift(file);
    if (recentMediaFiles.length > 10) recentMediaFiles.length = 10;
    handle?.loadPreviewMedia(file);
    updateChrome(`已加载媒体：${file.name}`);
    logEvent(`加载媒体 ${file.name}`);
  }
  mediaInput.value = "";
});
saveBtn.addEventListener("click", () => {
  run("save");
  dirty = false;
  updateChrome("已导出字幕文件");
  logEvent(`导出字幕 ${currentFilename}`);
});
toolsBtn.addEventListener("click", () => run("aegisub-tools"));
editorEl.addEventListener("aegisub-toolbar-toggle", () => {
  mainToolbar.hidden = !mainToolbar.hidden;
  document.getElementById("app")!.classList.toggle("toolbar-hidden", mainToolbar.hidden);
});

rateSelect.addEventListener("change", () => handle?.setPlaybackRate(Number(rateSelect.value)));
appFormatSelect.addEventListener("change", () => {
  handle?.runAegisubCommand(`subtitle/format/${appFormatSelect.value}`);
  if (handle) appFormatSelect.value = handle.getDoc().format;
});

languageSelect.addEventListener("change", () => {
  const text = handle?.getText() ?? SAMPLE_ASS;
  localStorage.setItem("aegisub-web.locale", languageSelect.value);
  setLocale(languageSelect.value);
  document.documentElement.lang = languageSelect.value === "zh" ? "zh-CN" : languageSelect.value;
  openDocument(text, currentFilename);
});

function applyTheme(theme: "light" | "dark"): void {
  document.documentElement.dataset.theme = theme;
  localStorage.setItem("aegisub-web.native-theme", theme);
  themeButton.textContent = theme === "dark" ? "☀" : "☾";
  themeButton.title = theme === "dark" ? "切换到浅色" : "切换到深色";
}
const initialTheme = (localStorage.getItem("aegisub-web.native-theme") as "light" | "dark" | null) ?? "light";
applyTheme(initialTheme);
themeButton.addEventListener("click", () => applyTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark"));

const desktopMac = /Macintosh/.test(navigator.userAgent) && navigator.maxTouchPoints < 2;
document.documentElement.dataset.platform = desktopMac ? "macos" : "default";
if (desktopMac) {
  const menubar = document.querySelector<HTMLElement>(".menubar")!;
  for (const id of ["menu-file", "menu-edit", "menu-view", "menu-subtitle", "menu-timing", "menu-video", "menu-audio", "menu-automation", "menu-tools", "menu-window", "menu-help"]) {
    const group = menubar.querySelector<HTMLElement>(`[data-menu="${id}"]`)?.parentElement;
    if (group) menubar.append(group);
  }
}

const menuButtons = [...document.querySelectorAll<HTMLButtonElement>(".menu-button")];
const menuPanels = [...document.querySelectorAll<HTMLElement>(".menu-panel")];
function closeMenus(): void {
  for (const panel of menuPanels) panel.hidden = true;
  for (const control of menuButtons) control.setAttribute("aria-expanded", "false");
}
for (const control of menuButtons) {
  control.addEventListener("click", (event) => {
    event.stopPropagation();
    const target = document.getElementById(control.dataset.menu || "");
    const wasOpen = target ? !target.hidden : false;
    closeMenus();
    if (target && !wasOpen) {
      target.hidden = false;
      control.setAttribute("aria-expanded", "true");
    }
  });
}
for (const item of document.querySelectorAll<HTMLButtonElement>("[data-command]")) {
  item.addEventListener("click", () => {
    run(item.dataset.command as EditorCommand);
    closeMenus();
  });
}
for (const item of document.querySelectorAll<HTMLButtonElement>("[data-aegisub-command]")) {
  item.addEventListener("click", () => {
    handle?.runAegisubCommand(item.dataset.aegisubCommand || "");
    closeMenus();
  });
}
for (const item of document.querySelectorAll<HTMLButtonElement>("[data-action]")) {
  item.addEventListener("click", () => {
    const action = item.dataset.action;
    if (action === "new") newDocument();
    if (action === "open") fileInput.click();
    if (action === "media") mediaInput.click();
    if (action === "theme") themeButton.click();
    if (action === "about") document.getElementById("about")?.showPopover();
    closeMenus();
  });
}
document.addEventListener("click", closeMenus);
document.addEventListener("keydown", (event) => {
  if (event.key === "Escape") closeMenus();
});

let dragDepth = 0;
document.addEventListener("dragenter", (event) => {
  event.preventDefault();
  dragDepth += 1;
  dropOverlay.hidden = false;
});
document.addEventListener("dragover", (event) => event.preventDefault());
document.addEventListener("dragleave", () => {
  dragDepth -= 1;
  if (dragDepth <= 0) {
    dragDepth = 0;
    dropOverlay.hidden = true;
  }
});
document.addEventListener("drop", async (event) => {
  event.preventDefault();
  dragDepth = 0;
  dropOverlay.hidden = true;
  const file = event.dataTransfer?.files?.[0];
  if (!file) return;
  if (/^(video|audio)\//.test(file.type) || /\.(mkv|mp4|webm|mov|avi|m4v|mp3|wav|flac|opus|ogg|oga|m4a|aac|alac|caf|aif|aiff)$/i.test(file.name)) {
    recentMediaFiles.unshift(file);
    handle?.loadPreviewMedia(file);
    updateChrome(`已加载媒体：${file.name}`);
  } else {
    await openSubtitleFile(file);
  }
});

interface InstallPromptEvent extends Event {
  prompt(): Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}
let installPrompt: InstallPromptEvent | null = null;
window.addEventListener("beforeinstallprompt", (event) => {
  event.preventDefault();
  installPrompt = event as InstallPromptEvent;
  installBtn.hidden = false;
});
installBtn.addEventListener("click", async () => {
  if (!installPrompt) return;
  await installPrompt.prompt();
  const choice = await installPrompt.userChoice;
  if (choice.outcome === "accepted") installBtn.hidden = true;
  installPrompt = null;
});

if ("serviceWorker" in navigator) {
  const allowPwaTest = new URLSearchParams(location.search).has("pwa-test");
  if (/^(localhost|127\.0\.0\.1)$/.test(location.hostname) && !allowPwaTest) {
    void navigator.serviceWorker.getRegistrations().then((registrations) => Promise.all(registrations.map((registration) => registration.unregister())));
    void caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith("aegisub-web-")).map((key) => caches.delete(key))));
  } else {
    window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));
  }
}
void navigator.storage?.persist?.().catch(() => false);

window.addEventListener("pagehide", (event) => {
  // Local media is never persisted. Explicitly tear down Blob URLs, decoder workers and
  // AudioContexts on refresh/navigation; a back-forward-cache page keeps its live state.
  if (!event.persisted) handle?.destroy();
});

openDocument(SAMPLE_ASS, "welcome.ass", false);
interface LaunchFileHandle { getFile(): Promise<File> }
interface LaunchQueueApi { setConsumer(consumer: (params: { files: LaunchFileHandle[] }) => void | Promise<void>): void }
const launchQueue = (window as unknown as { launchQueue?: LaunchQueueApi }).launchQueue;
launchQueue?.setConsumer(async ({ files }) => {
  const launched = files[0] ? await files[0].getFile() : null;
  if (!launched) return;
  if (/^(?:audio|video)\//.test(launched.type) || /\.(?:aac|aif|aiff|alac|avi|caf|flac|m4a|m4v|mkv|mov|mp3|mp4|oga|ogg|opus|wav|webm)$/i.test(launched.name)) {
    recentMediaFiles.unshift(launched);
    handle?.loadPreviewMedia(launched);
    updateChrome(`已加载媒体：${launched.name}`);
    logEvent(`从系统打开媒体 ${launched.name}`);
  } else {
    await openSubtitleFile(launched);
  }
});
const restoreVersion = documentVersion;
void loadLastProject().then((project) => {
  if (!project || project.filename === "welcome.ass" || documentVersion !== restoreVersion) return;
  openDocument(project.text, project.filename, false);
  autosaveEl.textContent = `已恢复 ${new Date(project.updatedAt).toLocaleString()}`;
});
